<div id="contentextended">
<h1>Clientes</h1>
 <p>ACQUAQUALITY<br />
    AIR QUALITY<br />
    ALICERCE ENGENHARIA LTDA<br />
    ALUNORTE- ALUMINA DO NORTE DO BRASIL S/A<br />
    ALVA COSMÉTICOS<br />
    AMBIENTECH TECNOLOGIA AMBIENTAL<br />
    ARCELOR MITTAL INOX<br />
ATLAS  COPCO<br />
BBM CONSULTORIA AMBIENTAL<br />
BETIM  QUÍMICA<br />
BUCKMAN<br />
CAFÉ FINO GRÃO<br />
CAIXA  ECONÔMICA FEDERAL<br />
CEMIG GERAÇÃO E TRANSMISSÃO S/A<br />
CIA BRASILEIRA DE BEBIDAS – AMBEV<br />
CIA  DE TECIDOS E TECELAGEM CEDRO CACHOEIRA<br />
CIA DE TECIDOS SANTANENSE<br />
CIA FABRIL MASCARENHAS<br />
CIA  INDUSTRIAL CATAGUASES<br />
CIA  MANUFATURA DE TECIDOS DE ALGODÃO<br />
CIA  MINEIRA DE METAIS<br />
CNT AMBIENTAL LTDA<br />
COMPANHIA ENERGÉTICA DE MINAS GERAIS - CEMIG<br />
DANONE S. A<br />
DIAMED LATINO AMÉRICA LTDA<br />
ECOSYSTEM  TECNOLOGIA AMBIENTAL<br />
EMPRESA GONTIJO DE TRANSPORTES LTDA<br />
FAMAP<br />
HOSPITAL MATER DEY<br />
HOSPITAL SEMPER<br />
HOTÉIS OTHON S.A<br />
INDAIÁ BRASIL ÁGUAS  MINERAIS<br />
IPIRANGA ASFALTO<br />
LABTEST DIAGNÓSTICA S/A<br />
LEME ENGENHARIA<br />
LIFE  CENTER<br />
LOGIN  ERRADIC<br />
MAQUINÉ EMPREENDIMENTOS S/A<br />
MEDIPHACOS<br />
MEGA  TÊXTIL<br />
MENDES JUNIOR TRADING E ENGENHARIA LTDA<br />
METFORM  S/A<br />
MINASAGRO  PRODUÇÃO EXPORTAÇÃO AGROINDUSTRIAL LTDA<br />
PERIPAN INDUSTRIAL LTDA<br />
SAINT GOBAIN <br />
SÃO  JOANENSE TÊXTIL S/A<br />
SEBRAE<br />
SHEC<br />
TECELAGEM MINAS REY<br />
TECNOMETAL ENGENHARIA E CONSTRUÇÕES MECÂNICAS LTDA<br />
TELEMAR<br />
TRIBUNAL  DE CONTAS<br />
TRIBUNAL  DE JUSTIÇA DE MINAS GERAIS<br />
TRIBUNAL  ELEITORAL DE MINAS GERAIS<br />
UNICAL  LDA<br />
UNIMED DE BELO HORIZONTE<br />
USIMINAS S/A<br />
WHITE MARTINS </p>

<h1>Parceiros</h1>
<p><a href="<?=site_url()?>/main/parceria_ecoar">ECOAR</a></p>
</div>
